### ISSUE TITLE
幫我買宵夜

### ISSUE THREAD

**Issue by StarrySkyYX** [113-1-DevOps/113-1-DevOps-team#5]

**Comment by Seveness1015** [comment]
我覺得全家的檸檬塔很好吃（就是有點甜要配茶）
![image](https://github.com/user-attachments/assets/bfe005eb-63f6-4b96-85e4-061a33c7c448)
![image](https://github.com/user-attachments/assets/9d8d4506-7e60-46b7-97a1-0029e5fc1219)
